Brmp 5410 category sub category
GSA/calc pull request #2508
Opened 2020-09-24 21:22 UTC by sushiljangili

2020-09-24 22:10 UTC, dsomalaraju approved these changes

2020-09-25 14:04 UTC, theodesta commented on frontend/source/js/data-explorer/components/optional-filters/optional-filters.jsx
> +import Subcategory from '../Subcategory';
When you get a chance, please make the directory name consistent.  For category you have 'category' but for subcategory you have 'Subcategory'.  All the others are lowercase.

2020-09-25 14:06 UTC, theodesta requested changes
Please look at my minor requests in comments. Thanks!

2020-09-25 14:06 UTC, theodesta commented on .vscode/launch.json
> +{
.vscode should be added to .gitignore

2020-10-22 12:55 UTC, closed without merging